# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{- if .Values.gcp.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-gw.resource.prefix" . }}-shared-synapse-configs
  labels:
    purpose: synapse-configs
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-gw.resource.prefix" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.sharedConfigs.fileStoreName }}/{{ .Values.gcp.fs.fileshares.sharedConfigs.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.sharedConfigs.ip }}
      volume: {{ .Values.gcp.fs.fileshares.sharedConfigs.fileShareName }}

{{ end }}
