# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apim-helm-gw.resource.prefix" . }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.deployment.am.gateway.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.wso2.deployment.am.gateway.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.wso2.deployment.am.gateway.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: {{ template "apim-helm-gw.resource.prefix" . }}
  template:
    metadata:
      annotations:
        checksum.am.gw.conf: {{ include (print $.Template.BasePath "/gateway/wso2am-gw-conf.yaml") . | sha256sum }}
        checksum.am.gw.conf.log4j2: {{ include (print $.Template.BasePath "/gateway/wso2am-gw-conf-log4j2.yaml") . | sha256sum }}
      labels:
        deployment: {{ template "apim-helm-gw.resource.prefix" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: deployment
                  operator: In
                  values:
                  - {{ template "apim-helm-gw.resource.prefix" . }}
              topologyKey: "topology.kubernetes.io/zone"
            weight: 100
      {{- if .Values.wso2.apim.secureVaultEnabled }} 
      {{- if .Values.aws.enabled }}
      serviceAccount: {{ .Values.aws.secretsManager.serviceAccountName }}
      {{- else if .Values.gcp.enabled }}
      serviceAccount: {{ .Values.gcp.secretsManager.serviceAccountName }}
      {{- end }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: wso2am-gateway
        image: {{ .Values.wso2.deployment.am.image.registry }}/{{ .Values.wso2.deployment.am.image.repository }}@{{ .Values.wso2.deployment.am.image.digest }}
        imagePullPolicy: {{ .Values.wso2.deployment.am.image.imagePullPolicy }}
        env:
        - name: PROFILE_NAME
          value: gateway-worker
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: JAVA_MEM_OPTS
          value: "-Xms{{ .Values.wso2.deployment.am.resources.jvm.memory.xms }} -Xmx{{ .Values.wso2.deployment.am.resources.jvm.memory.xmx }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost {{ add 8243 .Values.wso2.apim.portOffset }}
          initialDelaySeconds: {{ .Values.wso2.deployment.am.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.wso2.deployment.am.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.wso2.deployment.am.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost {{ add 8243 .Values.wso2.apim.portOffset }}
          initialDelaySeconds: {{ .Values.wso2.deployment.am.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.wso2.deployment.am.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.wso2.deployment.am.readinessProbe.failureThreshold }}
        lifecycle:
          preStop:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo "Pre stop hook triggered";
                  sleep 10;
                  echo "Shutdown APIM Server";
                  ${WSO2_SERVER_HOME}/bin/wso2server.sh stop
        resources:
          requests:
            memory: {{ .Values.wso2.deployment.am.resources.requests.memory }}
            cpu: {{ .Values.wso2.deployment.am.resources.requests.cpu }}
          limits:
            memory: {{ .Values.wso2.deployment.am.resources.limits.memory }}
            cpu: {{ .Values.wso2.deployment.am.resources.limits.cpu }}
        securityContext:
          runAsUser: {{ .Values.kubernetes.securityContext.runAsUser }}
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - all
        ports:
        - containerPort: {{ add 8280 .Values.wso2.apim.portOffset }}
          protocol: TCP
        - containerPort: {{ add 8243 .Values.wso2.apim.portOffset }}
          protocol: TCP
        - containerPort: {{ add 9763 .Values.wso2.apim.portOffset }}
          protocol: TCP
        - containerPort: {{ add 9443 .Values.wso2.apim.portOffset }}
          protocol: TCP
        volumeMounts:
        - name: shared-synapse-configs
          mountPath: /home/wso2carbon/wso2am-3.2.0/repository/deployment/server/synapse-configs
        - name: wso2am-gateway-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
          subPath: deployment.toml
        - name: wso2am-conf-entrypoint
          mountPath: /home/wso2carbon/docker-entrypoint.sh
          subPath: docker-entrypoint.sh
        {{- if .Values.wso2.apim.secureVaultEnabled }}
        - name: apim-secrets-volume
          mountPath: /mnt/secrets-store
          readOnly: true
        {{ end }}
        - name: apim-jks-volume
          mountPath: /home/wso2carbon/wso2-artifact-volume/repository/resources/security/{{ .Values.wso2.apim.configurations.security.keystores.internal.name }}
          subPath: {{ .Values.wso2.apim.configurations.security.keystores.internal.name }}
        - name: apim-jks-volume
          mountPath: /home/wso2carbon/wso2-artifact-volume/repository/resources/security/{{ .Values.wso2.apim.configurations.security.keystores.primary.name}}
          subPath: {{ .Values.wso2.apim.configurations.security.keystores.primary.name }}
        - name: apim-jks-volume
          mountPath: /home/wso2carbon/wso2-artifact-volume/repository/resources/security/{{ .Values.wso2.apim.configurations.security.keystores.tls.name}}
          subPath: {{ .Values.wso2.apim.configurations.security.keystores.tls.name }}
        - name: apim-jks-volume
          mountPath: /home/wso2carbon/wso2-artifact-volume/repository/resources/security/{{ .Values.wso2.apim.configurations.security.truststore.name}}
          subPath: {{ .Values.wso2.apim.configurations.security.truststore.name }}
        - name: apim-secret-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/security/secret-conf.properties
          subPath: secret-conf.properties
        - name: apim-log4j2-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/log4j2.properties
          subPath: log4j2.properties
        - name: apim-startup-conf
          mountPath: /home/wso2carbon/wso2-config-volume/bin/wso2server.sh
          subPath: wso2server.sh
      volumes:
      - name: shared-synapse-configs
        persistentVolumeClaim:
          claimName: {{ template "apim-helm-gw.resource.prefix" . }}-shared-synapse-configs
      - name: wso2am-gateway-conf
        configMap:
          name: {{ template "apim-helm-gw.resource.prefix" . }}-conf
      - name: wso2am-conf-entrypoint
        configMap:
          name: {{ template "apim-helm-gw.resource.prefix" . }}-conf-entrypoint
          defaultMode: 0407
      {{- if .Values.wso2.apim.secureVaultEnabled }}
      - name: apim-secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          {{ if .Values.azure.enabled }}
          volumeAttributes:
            secretProviderClass: {{ .Values.azure.keyVault.secretProviderClass }}
          nodePublishSecretRef:
            name: {{ template "apim-helm-gw.resource.prefix" . }}-secret-store-csi 
          {{- else if .Values.aws.enabled }}
          volumeAttributes:
            secretProviderClass: {{ .Values.aws.secretsManager.secretProviderClass }}
          {{- else if .Values.gcp.enabled }}
          volumeAttributes:
            secretProviderClass: {{ .Values.gcp.secretsManager.secretProviderClass }}
          {{- end }} 
      {{ end }}
      - name: apim-jks-volume
        secret:
          secretName: {{ .Values.wso2.apim.configurations.security.jksSecretName }}
      - name: apim-secret-conf
        configMap:
          name: {{ template "apim-helm-gw.resource.prefix" . }}-secret-conf
          defaultMode: 0407
      - name: apim-log4j2-conf
        configMap:
          name: {{ template "apim-helm-gw.resource.prefix" . }}-conf-log4j2
          defaultMode: 0407
      - name: apim-startup-conf
        configMap:
          name: {{ template "apim-helm-gw.resource.prefix" . }}-conf-startup
          defaultMode: 0407
