# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: {{ template "apim-helm-gw.fullname" . }}-service
  namespace : {{ .Release.Namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: {{ template "apim-helm-gw.fullname" . }}
  ports:
    # ports that this service should serve on
    - name: pass-through-http
      protocol: TCP
      port: 8280
    - name: pass-through-https
      protocol: TCP
      port: 8243
    - name: servlet-http
      protocol: TCP
      port: 9763
    - name: servlet-https
      protocol: TCP
      port: 9443
    - name: ws
      protocol: TCP
      port: 9099
    - name: wss
      protocol: TCP
      port: 8099
    - name: websub
      protocol: TCP
      port: 9021
    - name: websub-secure
      protocol: TCP
      port: 8021
